# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.


# NOTE: must set "Crossbow" as name to have the badge links working in the
# github comment reports!
name: Crossbow
on:
  push:
    branches:
      - "*-github-*"


jobs:
  package:
    name: Package Gandiva
    runs-on: macos-latest
    steps:
      - name: Checkout Arrow
        run: |
          git clone --no-checkout https://github.com/kou/arrow.git arrow
          git -C arrow fetch -t https://github.com/kou/arrow.git cpp-avoid-needless-c-ares-detection
          if [ $CROSSBOW_USE_COMMIT_ID = true ]; then git -C arrow checkout 056a87a2c15a65fc3d6b571cd44a7818e900b0c6; else git -C arrow checkout FETCH_HEAD; fi
          git -C arrow submodule update --init --recursive
      - name: Build Gandiva
        run: |
          cd arrow
          mkdir -p dist
          export ARROW_TEST_DATA=$PWD/testing/data
          set -e
          dev/tasks/gandiva-jars/build-cpp-osx.sh
          dev/tasks/gandiva-jars/build-java.sh
        env:
          OS_NAME: "osx"
          CHECK_SHARED_DEPENDENCIES: true
          MACOSX_DEPLOYMENT_TARGET: "10.11"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup Crossbow
        shell: bash
        run: pip install -e arrow/dev/archery[crossbow]
      - name: Upload artifacts
        shell: bash
        run: |
          archery crossbow \
          --queue-path $(pwd) \
          --queue-remote https://github.com/kou/crossbow.git \
          upload-artifacts \
          --sha build-274-github-gandiva-jar-osx \
          --tag build-274-github-gandiva-jar-osx \
          --pattern "arrow/dist/*.jar"
        env:
          CROSSBOW_GITHUB_TOKEN: ${{ secrets.CROSSBOW_GITHUB_TOKEN }}
